### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by rgieseke** [openclimatedata/nationally-determined-contributions#2]
To reduce confusion (this repo contains both NDCs and INDCs) with `ndcs` and `indcs` Data Packages.

Maybe 
`climate-action-plans`

`national-climate-plans`

See e.g. https://unfccc.int/news/national-climate-plans-ndcs-blueprints-for-a-global-transformation

cc @swillner

**Comment by swillner** [comment]
`paris-climate-plans` ?

**Comment by rgieseke** [comment]
`national-climate-plans` it is ... Less hits than action but seems to used somewhat and is has the "national" component.
